# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/noklam.github.io',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/noklam.github.io',
                'lib_path': 'noklam'},
  'syms': {'noklam.github.io.core': {'noklam.github.io.core.foo': ('core.html#foo', 'noklam.github.io/core.py')}}}
