project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      # - auto: "/*.ipynb"
      - blog/index.qmd

  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      # - about.qmd
      - text: "Blog"
        href: blog/index.qmd
      - icon: github
        href: https://github.com/noklam
      - icon: twitter
        href: https://twitter.com

  google-analytics: UA-83544344-5


metadata-files: [nbdev.yml, sidebar.yml]